"""Initial migration

Revision ID: d94fd1e4824a
Revises: 
Create Date: 2024-11-11 16:49:55.852906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd94fd1e4824a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('CustomerID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(), nullable=False),
    sa.Column('Email', sa.String(), nullable=False),
    sa.Column('Phone', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('CustomerID')
    )
    op.create_table('products',
    sa.Column('ProductID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ProductName', sa.String(), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('loyalty_cards',
    sa.Column('CardID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=True),
    sa.Column('BonusPoints', sa.Integer(), nullable=True),
    sa.Column('IssueDate', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['CustomerID'], ['customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('CardID')
    )
    op.create_table('orders',
    sa.Column('OrderID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CustomerID', sa.Integer(), nullable=True),
    sa.Column('OrderDate', sa.Date(), nullable=True),
    sa.Column('TotalAmount', sa.Float(), nullable=False),
    sa.Column('BonusUsed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CustomerID'], ['customers.CustomerID'], ),
    sa.PrimaryKeyConstraint('OrderID')
    )
    op.create_table('transactions',
    sa.Column('TransactionID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CardID', sa.Integer(), nullable=True),
    sa.Column('OrderID', sa.Integer(), nullable=True),
    sa.Column('TransactionDate', sa.Date(), nullable=True),
    sa.Column('PointsEarned', sa.Integer(), nullable=False),
    sa.Column('PointsSpent', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['CardID'], ['loyalty_cards.CardID'], ),
    sa.ForeignKeyConstraint(['OrderID'], ['orders.OrderID'], ),
    sa.PrimaryKeyConstraint('TransactionID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('orders')
    op.drop_table('loyalty_cards')
    op.drop_table('products')
    op.drop_table('customers')
    # ### end Alembic commands ###
